use_frameworks!

platform :ios, '9.0'

target 'SheetPresentationController_Example' do
  pod 'SheetPresentationController', :path => '../'

  target 'SheetPresentationController_Tests' do
    inherit! :search_paths

    
  end
end
